%% SensiMatrix 
%צריך לדאוג לכל הקלטים החשובים, שאולי כבר להגדיר אותם מראש (שנה, צמח ,קרקע,
%וכו')
%Input - parameter vector
%        State vector
% Output - RelSensiMatrix
%% calculate nominal states values and make a nominal parameter file
% Run model - > save state vector Ynom (it is a time series
%% Calculated   states values for all Parameter Changes Yp

%% Calculte Relative change (Dy/ynom)/(DP/Pnom)  {DY=Ynom-Yp}

function RC_t   = CalcRelCVec(Ynom_t,YpPlus_t,YpMinu_t,Pnom,Dp)
    %INPUT: 
    %       row - parameter, colomn - state
    %       Ynom - Ynom state row vector
    %       rows (the number of parameters for optimization
    %       Yp - state row vector where each row i is generated by a simulation with
    %       pi=pi+Dpi 
    %       Pnom - nominal value of all parameters, colomn vector
    %       Dp  - change of all parameters, row vector, 
    % OUTPUT - RelativeChangeMatrix
    N=length(Pnom);
    M=length(Ynom);
    YnomM=repelem(Ynom_t,N,1);
    DpM=repelem(Dp,1,M);
    PnomM=repelem(Pnom,1,M);
    DY=0.5*((YpPlus_t-Ynom)./DpM+(Ynom-YpMinu_t)./DpM);
    RC_t=PnomM./YnomM.*DY./DpM;
end